name: eiga
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  
  # Navigation & State Management
  go_router: ^18.0.0
  hooks_riverpod: ^3.4.2
  flutter_hooks: ^0.21.3+1

  # Storage & Database
  isar_community: ^3.3.2
  isar_community_flutter_libs: ^3.3.2
  shared_preferences: ^2.5.5
  flutter_secure_storage: ^11.0.0
  
  # Networking
  http: ^1.6.0
  dio: ^5.11.0
  cached_network_image: ^4.0.0

  # Media & UI
  media_kit: ^1.1.10+1
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.7
  ffmpeg_kit_flutter_new_audio: ^2.5.2
  fftea: ^1.1.2
  vad: ^0.0.8
  scrollable_positioned_list: ^0.3.8
  flutter_svg: ^2.3.0
  cupertino_icons: ^1.0.8
  wakelock_plus: ^1.2.8

  # Utilities
  path_provider: ^2.1.6
  file_picker: ^12.1.3
  window_manager: ^0.4.3
  screen_retriever: ^0.2.0
  path: ^1.9.1
  intl: ^0.20.2
  logger: ^2.7.0
  package_info_plus: ^10.2.1
  
  # Data Modeling
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  build_runner: ^2.13.1
  isar_community_generator: ^3.3.2
  freezed: ^3.2.5
  json_serializable: ^6.14.1
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  windows:
    generate: true
    image_path: "assets/icon/launcher_icon.png"
    icon_size: 256
  image_path: "assets/icon/launcher_icon.png"
  adaptive_icon_background: "#185FA5"
  adaptive_icon_foreground: "assets/icon/launcher_icon_foreground.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/models/silero_vad_v5.onnx
